name: BranchCI

on:
  push:
    branches-ignore:
      - 'main'
      - 'master'

jobs:
  branch-ci:
    name: Branch CI
    uses: molssi-seamm/devops/.github/workflows/BranchCI.yaml@main
    with:
      src : seamm
