name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    # Run on master by default Sunday morning at 3:30:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "30 3 * * 0"

jobs:
  ci:
    name: CI
    uses: molssi-seamm/devops/.github/workflows/CI.yaml@main
    with:
      src : seamm
